//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.APICore.CustomModel
{
    using System;
     
    public partial class I_Sls_TR_Invoice
    {
        public int InvoiceID { get; set; }
        public Nullable<int> TrNo { get; set; } 
        public Nullable<int> Status { get; set; } 
        public DateTime TaxUploadDate { get; set; } 
        public string DocUUID { get; set; } 
    }
}
