//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitValue
    {
        public int unitValueID { get; set; }
        public string currencySold { get; set; }
        public Nullable<decimal> amountEGP { get; set; }
        public string Desc { get; set; }
    }
}
